// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALbA9vACo-IveKR-2Nj-85Z1djVwMuvjo',
    appId: '1:45932779821:web:d84fc3ce53ddacb405dba4',
    messagingSenderId: '45932779821',
    projectId: 'spendmate-63771',
    authDomain: 'spendmate-63771.firebaseapp.com',
    storageBucket: 'spendmate-63771.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5eZL72t3ZNQPhT3rV1n7NpkVSibSouY',
    appId: '1:45932779821:android:93b6138079e4581705dba4',
    messagingSenderId: '45932779821',
    projectId: 'spendmate-63771',
    storageBucket: 'spendmate-63771.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjy_Arr22hns2qaXDqyncZ5IrrtKWQ7M',
    appId: '1:45932779821:ios:6aa5cb9adcaf2da505dba4',
    messagingSenderId: '45932779821',
    projectId: 'spendmate-63771',
    storageBucket: 'spendmate-63771.firebasestorage.app',
    iosBundleId: 'com.example.spendmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjy_Arr22hns2qaXDqyncZ5IrrtKWQ7M',
    appId: '1:45932779821:ios:6aa5cb9adcaf2da505dba4',
    messagingSenderId: '45932779821',
    projectId: 'spendmate-63771',
    storageBucket: 'spendmate-63771.firebasestorage.app',
    iosBundleId: 'com.example.spendmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALbA9vACo-IveKR-2Nj-85Z1djVwMuvjo',
    appId: '1:45932779821:web:1ad90534241e2c3c05dba4',
    messagingSenderId: '45932779821',
    projectId: 'spendmate-63771',
    authDomain: 'spendmate-63771.firebaseapp.com',
    storageBucket: 'spendmate-63771.firebasestorage.app',
  );
}
